2022-05-18 08:40:25,772 - python logging模块.py[line:47] - ERROR: Exception occurred[Errno 2] No such file or directory: 'sklearn.txt'
Traceback (most recent call last):
  File "D:/BaiduNetdiskDownload/python-demo/python小案例/python logging模块.py", line 43, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2022-05-18 08:40:25,773 - python logging模块.py[line:55] - INFO: Finish
2022-05-18 08:41:40,930 - python logging模块.py[line:55] - INFO: Finish
2022-05-18 08:43:22,647 - python logging模块.py[line:47] - ERROR: Exception occurred
Traceback (most recent call last):
  File "D:/BaiduNetdiskDownload/python-demo/python小案例/python logging模块.py", line 43, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2022-05-18 08:43:22,648 - python logging模块.py[line:56] - INFO: Finish
